### ISSUE TITLE
Run this app.. Possible to run in emulator or real Device?

### ISSUE THREAD

**Issue by andhicapratama** [GoBelieveIO/voip_android#2]
I just start this app. So if i want to run this. can it be on emulator or have to be on real device.
Because I want to know the process of this project but, Little confused about running this app.

Thanks

**Comment by andhicapratama** [comment]
Is it peer to peer voip, right.
This is not using server right..??

I'm still learning about making android app.

**Comment by richmonkey** [comment]
need real device.
need server to transfer signal, but audio/video data is peer to peer.
reference to webrtc

**Comment by andhicapratama** [comment]
Thanks for the answer, I 'm still learning your code. 

Thanks a lot.
